application: gaemeta
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /admin.*
  login: required
  script: gaemeta.wsgi.application

- url: /.*
  script: gaemeta.wsgi.application
